# Generated by Django 4.2.14 on 2024-08-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_message_status_changed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status_changed_at',
        ),
    ]
